SVE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth.views import LoginView, logout_then_login
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^autenticacion/', include('apps.Registro.urls')),
    path('autenticacion/', include('django.contrib.auth.urls')),
    url(r'^enfermedades/', include('apps.Enfermedades.urls')),
    url(r'^inicio/', include('apps.Riesgos.urls')),
    url(r'^login/',LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/Enfermedades/models.py
from django.db import models

# Create your models here.
class Enfermedad(models.Model):
    identificador =  models.CharField(primary_key=True, max_length=10)
    titulo = models.CharField(max_length=100)
    definicion = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.titulo

    def def_corta(self):
        return self.definicion[:50]

apps/Riesgos/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User


# Create your models here.
# Modelo que permite crear la tabla Riesgo en la base de datos
# id: cadena que identifica a un riesgo
# nombre: nombre del riesgo
# models.Model: instancia del modelo


class Riesgo(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return '{} {}'.format(self.nombre, self.id)


# Modelo que permite crear la tabla Test en la base de datos
# id: cadena que identifica a un test
# idRiesgo: foranea que permite la relacion de uno a uno el riesgo al que pertenece
# fecha: fecha de la creacion del Test
# descripcion: introduccion de la funcionalidad del test
# estado: estado en el que se encuentra el test True o false, por defecto el True


class TestME(models.Model):
    id = models.AutoField(primary_key=True)
    idRiesgo = models.ForeignKey(Riesgo, null=False, on_delete=models.CASCADE)
    fecha = models.DateTimeField(null=False, default=datetime.datetime.now())
    descripcion = models.CharField(max_length=500, null=False, default='Riesgo Musculo Esqueletico')
    estado = models.BooleanField(default=True)
    usuario = models.ForeignKey(User, models.ForeignKey(User, null=False, on_delete=models.CASCADE))
    diagnostico = models.CharField(max_length=30, null=True)


class Cargo(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(null=False, max_length=30)
    descripcion = models.CharField(null=False, max_length=200)

    def __str__(self):
        return '{} {}'.format(self.nombre, self.id)


class Dependencia(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(null=False, max_length=30)
    descripcion = models.CharField(null=False, max_length=200)

    def __str__(self):
        return '{} {}'.format(self.nombre, self.id)


class PerfilDemografico(models.Model):
    id0 = models.AutoField(primary_key=True)
    test0 = models.OneToOneField(TestME, null=False, on_delete=models.CASCADE)
    cedula0 = models.IntegerField(null=False)
    nombre0 = models.CharField(null=False, max_length=30)
    apellido0 = models.CharField(null=False, max_length=30)
    sexo0 = models.BooleanField(null=False)
    peso0 = models.DecimalField(null=False, max_digits=5, decimal_places=2)
    manoDominante0 = models.CharField(null=False, max_length=10)
    cargo0 = models.ForeignKey(Cargo, null=False, on_delete=models.CASCADE)
    dependencia0 = models.ForeignKey(Dependencia, null=False, on_delete=models.CASCADE)
    antiguedadCargo0 = models.DecimalField(null=False, max_digits=5, decimal_places=2)
    actividadFisica0 = models.CharField(null=False, max_length=30)
    horasActividadFisi0 = models.IntegerField(null=False)
    variaSuJornada0 = models.BooleanField(null=False)


# Modelo de la tabla en la que se guardan los datos de los desordenes musculo esqueleticos
# usuario : usuario que llena los datos
# test : el test por defecto es el musculo esqueletico ME valor:1
# lugarMolestia: 1 lado izquierdo 2 lado derecho 3 ambos
# laMolestiaEs: 1 Dolor 2 hormigueo 3 malestar 4 adormecimiento
# molestiaSepresenta: 1 al realizar mi trabajo 2 todo el tiempo 3 al final del dia 4 al final de la semana 5 en mi casa
# seEfectuaMolestia: 1 si realizo movimientos con el hombro hacia delante 2 si realizo movimientos con el hombro hacia atras
# intensidadMolestia: 1 a 10 que tanto dolor siente la persona
# otraActividadMolestaAu: 1 si 2 no
# otraActividadMolestaDis: 1 si 2 no
# duracionMolestia: 1 menos de dos horas 2 mas de dos horas 3 intermitente durante el dia 4 constante todo el dia
# interfirioTrabajo: 1 no 2 poca interferencia 3 interferencia sustancialmente

class HombroME(models.Model):
    id1 = models.AutoField(primary_key=True)
    test1 = models.OneToOneField(TestME, null=False, on_delete=models.CASCADE)
    lugarMolestia1 = models.IntegerField(null=True)
    molestiaSepresenta1 = models.IntegerField(null=True)
    laMolestiaEs1 = models.IntegerField(null=True)
    seEfectuaMolestia1 = models.IntegerField(null=True)
    intensidadMolestia1 = models.IntegerField(null=True)
    otraActividadMolestaAu1 = models.IntegerField(null=True)
    otraActividadMolestaDis1 = models.IntegerField(null=True)
    duracionMolestia1 = models.IntegerField(null=True)
    interfirioTrabajo1 = models.IntegerField(null=True)


class CuelloME(models.Model):
    id2 = models.AutoField(primary_key=True)
    test2 = models.OneToOneField(TestME, null=False, on_delete=models.CASCADE)
    lugarMolestia2 = models.IntegerField(null=True)
    molestiaSepresenta2 = models.IntegerField(null=True)
    laMolestiaEs2 = models.IntegerField(null=True)
    seEfectuaMolestia2 = models.IntegerField(null=True)
    intensidadMolestia2 = models.IntegerField(null=True)
    otraActividadMolestaAu2 = models.IntegerField(null=True)
    otraActividadMolestaDis2 = models.IntegerField(null=True)
    duracionMolestia2 = models.IntegerField(null=True)
    interfirioTrabajo2 = models.IntegerField(null=True)


class CodoME(models.Model):
    id3 = models.AutoField(primary_key=True)
    test3 = models.OneToOneField(TestME, null=False, on_delete=models.CASCADE)
    lugarMolestia3 = models.IntegerField(null=True)
    molestiaSepresenta3 = models.IntegerField(null=True)
    laMolestiaEs3 = models.IntegerField(null=True)
    seEfectuaMolestia3 = models.IntegerField(null=True)
    intensidadMolestia3 = models.IntegerField(null=True)
    otraActividadMolestaAu3 = models.IntegerField(null=True)
    otraActividadMolestaDis3 = models.IntegerField(null=True)
    duracionMolestia3 = models.IntegerField(null=True)
    interfirioTrabajo3 = models.IntegerField(null=True)


class ManoME(models.Model):
    id4 = models.AutoField(primary_key=True)
    test4 = models.OneToOneField(TestME, null=False, on_delete=models.CASCADE)
    lugarMolestia4 = models.IntegerField(null=True)
    molestiaSepresenta4 = models.IntegerField(null=True)
    laMolestiaEs4 = models.IntegerField(null=True)
    seEfectuaMolestia4 = models.IntegerField(null=True)
    intensidadMolestia4 = models.IntegerField(null=True)
    otraActividadMolestaAu4 = models.IntegerField(null=True)
    otraActividadMolestaDis4 = models.IntegerField(null=True)
    duracionMolestia4 = models.IntegerField(null=True)
    interfirioTrabajo4 = models.IntegerField(null=True)


class EspaldaBajaME(models.Model):
    id5 = models.AutoField(primary_key=True)
    test5 = models.OneToOneField(TestME, null=False, on_delete=models.CASCADE)
    lugarMolestia5 = models.IntegerField(null=True)
    molestiaSepresenta5 = models.IntegerField(null=True)
    laMolestiaEs5 = models.IntegerField(null=True)
    seEfectuaMolestia5 = models.IntegerField(null=True)
    intensidadMolestia5 = models.IntegerField(null=True)
    otraActividadMolestaAu5 = models.IntegerField(null=True)
    otraActividadMolestaDis5 = models.IntegerField(null=True)
    duracionMolestia5 = models.IntegerField(null=True)
    interfirioTrabajo5 = models.IntegerField(null=True)


class EspaldaDorsalME(models.Model):
    id6 = models.AutoField(primary_key=True)
    test6 = models.OneToOneField(TestME, null=False, on_delete=models.CASCADE)
    lugarMolestia6 = models.IntegerField(null=True)
    molestiaSepresenta6 = models.IntegerField(null=True)
    laMolestiaEs6 = models.IntegerField(null=True)
    seEfectuaMolestia6 = models.IntegerField(null=True)
    intensidadMolestia6 = models.IntegerField(null=True)
    otraActividadMolestaAu6 = models.IntegerField(null=True)
    otraActividadMolestaDis6 = models.IntegerField(null=True)
    duracionMolestia6 = models.IntegerField(null=True)
    interfirioTrabajo6 = models.IntegerField(null=True)


class SabiasQue(models.Model):
    id = models.AutoField(primary_key=True)
    idRiesgo = models.ForeignKey(Riesgo, null=False, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100, null=False)
    descripcion = models.CharField(max_length=500, null=False)
    demostracion = models.ImageField(upload_to='demostraciones', null=True)


class PosibleEnfermedad(models.Model):
    id = models.AutoField(primary_key=True)
    idRiesgo = models.ForeignKey(Riesgo, null=False, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100, null=False)
    descripcion = models.CharField(max_length=400, null=False)

    def __str__(self):
        return '{}'.format(self.nombre)


class DefinicionEnfermedad(models.Model):
    id = models.AutoField(primary_key=True)
    enfermedad = models.ForeignKey(PosibleEnfermedad, null=False, on_delete=models.CASCADE)
    descripcion1 = models.CharField(null=False, max_length=400)
    imagen = models.ImageField(upload_to='photo', null=True)


class poblacion(models.Model):
    identificacion = models.AutoField(primary_key=True)
    correo = models.EmailField(max_length=100, null=False, blank=True, unique=True)
    Riesgo = models.ForeignKey(Riesgo, on_delete=models.CASCADE)

    def __str__(self):
        return '{} {} {}'.format(self.correo, self.identificacion, self.Riesgo)

templates/RiesgoME/eliminarDefEnfer.html
{% extends "base_generic.html" %}

 {% block content %}
 {% if perms.enfermedad.delete_enfermedad %}

<form method="post" align="center">
            <div align="center">


            {% csrf_token %}
                <h3>¿Desea eliminar la siguiente definición de enfermedad? {{definicionEnfermedad.descripcion}}</h3>


                </div>
               <button  class="btn btn-danger" type="submit"  >Si, Eliminar</button>
                <a class="btn btn-default" href="/inicio/administrarSVE/listaRecomendaciones">Cancelar</a>
    



        </form>
{%endif%}
   {% endblock %}

templates/RiesgoME/eliminarEnfermedadME.html
{% extends "base_generic.html" %}

 {% block content %}
 {% if perms.enfermedad.delete_enfermedad %}

<form method="post" align="center">
            <div align="center">


            {% csrf_token %}
                <h3>¿Desea eliminar la siguiente enfermedad? {{posibleEnfermedad.nombre}}</h3>


                </div>
                <button class="btn btn-danger" type="submit">Si, Eliminar</button>
                <a class="btn btn-default" href="/inicio/administrarSVE/musculoEsqueletico/enfermedadesME">Cancelar</a>



        </form>
{%endif%}
   {% endblock %}

templates/RiesgoME/eliminarPoblacionME.html
{% extends "base_generic.html" %}

 {% block content %}
 {% if perms.poblacion.delete_poblacion %}
<form method="post" align="center">
            <div align="center">


            {% csrf_token %}
                <h3>¿Desea eliminar el siguiente correo de la poblacion? {{Poblacion.correo}}</h3>


                </div>
               <button  class="btn btn-danger" type="submit"  >Si, Eliminar</button>
                <a class="btn btn-default" href="/inicio/administrarSVE/poblacionSVE/lista">Cancelar</a>



        </form>
{% else %}
no tiene permisos para ver esta pagina
{%endif%}
{% endblock %}

templates/RiesgoME/enfermedadesME.html
{% extends "base_generic.html" %}

   {% block content %}
                     {% if perms.enfermedad.add_enfermedad %}

        <h1 align="center">
            Lista de enfermedades
        </h1>
<table align="center" border="1">
    {% if posibleEnfermedades %}
<thead>
            <tr>
                    <td align="center">Ingresar</td>
                <td align="center">Nombre</td>
                 <td align="center">Descripcion</td>
                 {% if perms.enfermedad.enfermedad and perms.enfermedad.delete_enfermedad %}
            <td align="center">Acciones</td>
                {% endif %}
            </tr>

        </thead>
    {%endif%}
        <tbody>

        {% if posibleEnfermedades %}
        {% for posibleEnfermedad in posibleEnfermedades %}
            <tr>
                <td>&nbsp; <a class="btn btn-primary"  onclick="verInformacionEnf({{posibleEnfermedad.id}} )">{{posibleEnfermedad.nombre}}</a> &nbsp;</td>
                <td>&nbsp; {{posibleEnfermedad.nombre}} &nbsp;</td>
                <td>&nbsp; {{posibleEnfermedad.descripcion}} &nbsp;</td>
                <td>&nbsp; <a class="btn btn-primary"  onclick="redirigirEnfermedadEditar({{posibleEnfermedad.id}} )">Editar</a> <a  class="btn btn-danger"  onclick="redirigirEnfermedadEliminar({{posibleEnfermedad.id}} )">Eliminar</a>&nbsp;</td>

            </tr>


        {% endfor %}




            <script type="text/javascript">

                function verInformacionEnf(id){
                   var id1 = id;
                  location.href = "/inicio/administrarSVE/aggenfermedad/informacionEnf/" + id1;
                   }

                  function redirigirEnfermedadEditar(id){
                   var id1 = id;
                  location.href = "/inicio/administrarSVE/aggenfermedad/editar/" + id1;
                   }

                   function redirigirEnfermedadEliminar(id){
                   var id1 = id;
                  location.href = "/inicio/administrarSVE/aggenfermedad/eliminar/" + id1;
                   }


            </script>

        {% else %}

        <h1 align="center">
            No hay enfermedades registradas.
        </h1>
        {% endif %}
        </tbody>
    </table>
<br>
<div align="center">
        <a href=" /inicio/administrarSVE/aggenfermedad" class="enlace">Volver</a> &nbsp;
        
</div>
<br>
{% endif %}
{% endblock %}

templates/RiesgoME/enviarCorreoME.html
{% extends "base_generic.html" %}

 {% block content %}
 {% if perms.poblacion.add_poblacion %}

        <body>
        <h1>Se ha enviado los mensajes a su población del riesgo musculo-esqueletico.</h1>
             <a class="enlace" href="/inicio/administrarSVE/poblacionSVE/lista">Aceptar</a>

        </body>
{% else %}
<h1 align="center"> No tiene permisos para ver esta pagina.</h1>
{%endif%}
    {% endblock %}

templates/RiesgoME/informacionEnf.html
{% extends "base_generic.html" %}

   {% block content %}
 {% if perms.enfermedad.add_enfermedad  %}
        <h1 align="center">
            Lista de personas
        </h1>
<table align="center" border="1">
<thead>
            <tr>
                <td align="center">descripción</td>
                <td align="center">imagen relacionada</td>
                 {% if perms.enfermedad.change_enfermedad and perms.enfermedad.delete_enfermedad %}
                <td align="center">acciones</td>
                {%endif%}
            </tr>

        </thead>
        <tbody>

        {% if definicionEnfermedades %}
        {% for definicionEnfermedad in definicionEnfermedades %}
            <tr>
                <td>&nbsp; {{definicionEnfermedad.descripcion1}} &nbsp;</td>
                <td>&nbsp;<figure><img src="/imageEnfermedad/{{definicionEnfermedad.imagen}}" width="200" height="200"> </figure> &nbsp;</td>
                <td>&nbsp; <a class="btn btn-primary"  onclick="redirigirEnfeEditar({{definicionEnfermedad.id}} )">Editar</a> <a  class="btn btn-danger"  onclick="redirigirEnferEliminar({{definicionEnfermedad.id}} )">Eliminar</a>&nbsp;</td>

            </tr>


        {% endfor %}

        




            <script type="text/javascript">
                  function redirigirEnfeEditar(defEnf){
                   var defEnf1 = defEnf;
                  location.href = "/inicio/administrarSVE/aggenfermedad/defEnfMEEdit/" + defEnf1;
                   }

                   function redirigirEnferEliminar(defEnf){
                   var defEnf1 = defEnf;
                  location.href = "/inicio/administrarSVE/aggenfermedad/defEnfMEEliminar/" + defEnf1;
                   }


            </script>

        {% else %}

        <h1>
            No hay personas registradas
        </h1>
        {% endif %}
        </tbody>
    </table>
<br>
<div align="center">
        <a href="/inicio/administrarSVE/poblacionSVE" class="enlace">Volver</a> &nbsp;
        <a href="/inicio/administrarSVE/poblacionSVE/lista/correos" class="enlace">Enviar correos</a>
</div>
<br>
{% else %}
no tiene permisos para ver esta pagina
{%endif%}
{% endblock %}

templates/RiesgoME/listaPoblacion.html
{% extends "base_generic.html" %}

   {% block content %}
                         {% if perms.poblacion.add_poblacion %}

        <h1 align="center">
            Lista de personas
        </h1>
<table align="center" border="1">
{%if poblaciones%}
    <thead>

            <tr>
                <td align="center">Correo</td>
                 <td align="center">Riesgo</td>
                {% if perms.poblacion.change_poblacion and perms.poblacion.delete_poblacion %}

                <td align="center">Acciones</td>
                {%endif%}
            </tr>

        </thead>
    {%endif%}
        <tbody>

        {% if poblaciones %}
        {% for poblacion in poblaciones %}
            <tr>
                <td>&nbsp; {{poblacion.correo}} &nbsp;</td>
                <td>&nbsp; {{poblacion.Riesgo.nombre}} &nbsp;</td>
                <td>&nbsp; <a class="btn btn-primary"  onclick="redirigirCorreoEditar({{poblacion.identificacion}} )">Editar</a> <a  class="btn btn-danger"  onclick="redirigirCorreoEliminar({{poblacion.identificacion}} )">Eliminar</a>&nbsp;</td>

            </tr>


        {% endfor %}




            <script type="text/javascript">
                  function redirigirCorreoEditar(emailUser){
                   var emailUser1 = emailUser;
                  location.href = "/inicio/administrarSVE/poblacionSVE/editar/" + emailUser;
                   }

                   function redirigirCorreoEliminar(emailUser){
                   var emailUser1 = emailUser;
                  location.href = "/inicio/administrarSVE/poblacionSVE/eliminar/" + emailUser;
                   }


            </script>

        {% else %}

        <h1 align="center">
            No hay personas registradas
        </h1>
        {% endif %}
        </tbody>
    </table>
<br>
<div align="center">
        <a href="/inicio/administrarSVE/poblacionSVE" class="enlace">Volver</a> &nbsp;
        {%if poblaciones %}
        <a href="/inicio/administrarSVE/poblacionSVE/lista/correos" class="enlace">Enviar correos</a>
    {%endif%}
</div>
<br>

{% else %}
<h1 align="center"> No tiene permisos para ver esta página.</h1>
{%endif%}
{% endblock %}

templates/RiesgoME/mensajeME.html
{% extends "base_generic.html" %}

 {% block content %}

    {% endblock %}

templates/RiesgoME/musculoEsqueletico.html
{% extends "base_generic.html" %}

 {% block content %}

 </body>

        <body>
        <h1 align="center">Riesgo Musculo-Esquelético</h1>

        <div id="listageneral">
        <ul class="cards-list">
           <li class="ci-4 cards-item">
             <div class="card">
              <a href="/inicio/musculoEsqueletico/enfermedadesME" class="card-container" rel="keep-params">
                    <div class="card-icon card-icon-5">
                        <i class="icono fas fa-procedures"></i>
                    </div>
                    <div class="card-title-container">
                        <h3 class="card-title">Lista de enfermedades</h3>
                    </div>
              </a>
             </div>
           </li>
           <li class="ci-4 cards-item">
             <div class="card">
                <a href="/inicio/musculoEsqueletico/testME/iniciarTestMEPiloto" class="card-container" rel="keep-params">
                    <div class="card-icon card-icon-7">
                        <i class="icono fas fa-file-alt"></i>
                    </div>
                    <div class="card-title-container">
                        <h3 class="card-title">Realizar test</h3>
                    </div>
                </a>
             </div>
           </li>
        </ul>
    </div>


        </body>
    {% endblock %}

templates/RiesgoME/testME.html
{% extends "base_generic.html" %}

 {% block content %}
        <body>


            <a  href="/inicio/musculoEsqueletico/testME/enviado">enviar</a>


        </body>
    {% endblock %}